# Define default values for customization
replicas: 2
image:
  name: nodeJsBackend
service:
  type: LoadBalancer  # Adjust service type (e.g. NodePort) if needed
configMap:
  PORT: 3000  # Listening port
  MONGODB_URI: mongodb:27017/vdt2024
secrets:
  MONGODB_USERNAME: bW9uZ29hZG1pbg==
  MONGODB_PASSWORD: c2VjdXJlcGFzc3dvcmQ=
# Add values for ConfigMap and Secret data if applicable
