# Define default values for customization
appVersion: 0.1.13
replicas: 2
image:
  name: agrainofsand/nodejs-backend
service:
  type: LoadBalancer  # Adjust service type (e.g. NodePort) if needed
configMap:
  PORT: 3000  # Listening port
  MONGODB_URI: mongodb:27017/vdt2024
secrets:
  MONGODB_USERNAME: mongoadmin
  MONGODB_PASSWORD: securepassword
# Add values for ConfigMap and Secret data if applicable
