apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prefix }}-deployment
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.prefix }}
  template:
    metadata:
      labels:
        app: {{ .Values.prefix }}
    spec:
      containers:
      - name: my-app
        image: '{{ .Values.image.name }}:{{ .Values.appVersion }}'
        ports:
        - containerPort: {{ .Values.configMap.PORT }}
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.prefix }}-config
              key: PORT
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.prefix }}-config
              key: MONGODB_URI
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.prefix }}-secret
              key: MONGODB_USERNAME
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.prefix }}-secret
              key: MONGODB_PASSWORD
        # Add references for other secrets or config maps
        # ...
